
project_id = "imqdasdegvltcgzklbtj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }} ."

[functions.createGrab]
verify_jwt = false

[functions.getGrab]
verify_jwt = false

[functions.getGrabs]
verify_jwt = false

[functions.validateGrab]
verify_jwt = false

[functions.generateValidationCode]
verify_jwt = false

[functions.issueCredits]
verify_jwt = false

[functions.useGrab]
verify_jwt = false

[functions.mock-payment]
verify_jwt = false

[functions.processCredits]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.sendMerchantNotification]
verify_jwt = false

[analytics]
enabled = false
