// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imqdasdegvltcgzklbtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltcWRhc2RlZ3ZsdGNnemtsYnRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzA4NTMsImV4cCI6MjA3MTAwNjg1M30.cYM4Mb0xMkqVsJmvXNmS7CgNPiWlk2x1mMOIWbGc_aY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});